// Code generated by configgen.go; EDIT AT YOUR OWN RISK.

package main

import (
    "errors"
    "os"
    "strings"
)

const (
    OLXTRACKER_OLXAPIAUTH_CLIENTID_ENV = "OLXTRACKER_OLXAPIAUTH_CLIENTID"
    OLXTRACKER_OLXAPIAUTH_CLIENTSECRET_ENV = "OLXTRACKER_OLXAPIAUTH_CLIENTSECRET"
)

var (
    ErrOlxtrackerOlxapiauthClientidEnvMissing = errors.New(OLXTRACKER_OLXAPIAUTH_CLIENTID_ENV)
    ErrOlxtrackerOlxapiauthClientsecretEnvMissing = errors.New(OLXTRACKER_OLXAPIAUTH_CLIENTSECRET_ENV)
)

func LoadConfig() (Config, error) {
    var config Config
    var missingVars []error
    var formatVars []error
    val_OlxApiAuth_ClientID, ok := os.LookupEnv(OLXTRACKER_OLXAPIAUTH_CLIENTID_ENV)
    if !ok {
        missingVars = append(missingVars, ErrOlxtrackerOlxapiauthClientidEnvMissing)
    } else {
        config.OlxApiAuth.ClientID = val_OlxApiAuth_ClientID
    }
    val_OlxApiAuth_ClientSecret, ok := os.LookupEnv(OLXTRACKER_OLXAPIAUTH_CLIENTSECRET_ENV)
    if !ok {
        missingVars = append(missingVars, ErrOlxtrackerOlxapiauthClientsecretEnvMissing)
    } else {
        config.OlxApiAuth.ClientSecret = val_OlxApiAuth_ClientSecret
    }

    if len(missingVars) > 0 || len(formatVars) > 0 {
        var verr error
        if len(missingVars) > 0 {
            verr = errors.Join(verr, MissingEnvVarsError{vars: missingVars})
        }
        if len(formatVars) > 0 {
            verr = errors.Join(verr, InvalidEnvVarsError{vars: missingVars})
        }
        return Config{}, verr
    }

    return config, nil
}

type MissingEnvVarsError struct {
	vars []error
}

func (m MissingEnvVarsError) Unwrap() []error {
	return m.vars
}

func (m MissingEnvVarsError) Error() string {
	if len(m.vars) == 0 {
		return ""
	}
	varsstr := make([]string, 0, len(m.vars))
	for _, v := range m.vars {
		varsstr = append(varsstr, v.Error())
	}
	return "envs " + strings.Join(varsstr, ",") + " are not set"
}

type InvalidEnvVarsError struct {
	vars []error
}

func (m InvalidEnvVarsError) Unwrap() []error {
	return m.vars
}

func (m InvalidEnvVarsError) Error() string {
	if len(m.vars) == 0 {
		return ""
	}
	varsstr := make([]string, 0, len(m.vars))
	for _, v := range m.vars {
		varsstr = append(varsstr, v.Error())
	}
	return "envs " + strings.Join(varsstr, ",") + " have an invalid value"
}
