// Code generated by configgen.go; EDIT AT YOUR OWN RISK.

package config

import (
    "errors"
    "os"
    "strconv"
    "strings"
)

const (
    OLXTRACKER_PORT_ENV = "OLXTRACKER_PORT"
    OLXTRACKER_POSTGRES_USER_ENV = "OLXTRACKER_POSTGRES_USER"
    OLXTRACKER_POSTGRES_PASSWORD_ENV = "OLXTRACKER_POSTGRES_PASSWORD"
    OLXTRACKER_POSTGRES_HOST_ENV = "OLXTRACKER_POSTGRES_HOST"
    OLXTRACKER_POSTGRES_PORT_ENV = "OLXTRACKER_POSTGRES_PORT"
    OLXTRACKER_POSTGRES_DATABASE_ENV = "OLXTRACKER_POSTGRES_DATABASE"
    OLXTRACKER_POSTGRES_SCHEMA_ENV = "OLXTRACKER_POSTGRES_SCHEMA"
)

var (
    ErrOlxtrackerPortEnvMissing = errors.New(OLXTRACKER_PORT_ENV)
    ErrOlxtrackerPostgresUserEnvMissing = errors.New(OLXTRACKER_POSTGRES_USER_ENV)
    ErrOlxtrackerPostgresPasswordEnvMissing = errors.New(OLXTRACKER_POSTGRES_PASSWORD_ENV)
    ErrOlxtrackerPostgresHostEnvMissing = errors.New(OLXTRACKER_POSTGRES_HOST_ENV)
    ErrOlxtrackerPostgresPortEnvMissing = errors.New(OLXTRACKER_POSTGRES_PORT_ENV)
    ErrOlxtrackerPostgresPortEnvInvalid = errors.New(OLXTRACKER_POSTGRES_PORT_ENV)
    ErrOlxtrackerPostgresDatabaseEnvMissing = errors.New(OLXTRACKER_POSTGRES_DATABASE_ENV)
    ErrOlxtrackerPostgresSchemaEnvMissing = errors.New(OLXTRACKER_POSTGRES_SCHEMA_ENV)
)

func LoadConfig() (Config, error) {
    var config Config
    var missingVars []error
    var formatVars []error
    val_Port, ok := os.LookupEnv(OLXTRACKER_PORT_ENV)
    if !ok {
        missingVars = append(missingVars, ErrOlxtrackerPortEnvMissing)
    } else {
        config.Port = val_Port
    }
    val_Postgres_User, ok := os.LookupEnv(OLXTRACKER_POSTGRES_USER_ENV)
    if !ok {
        missingVars = append(missingVars, ErrOlxtrackerPostgresUserEnvMissing)
    } else {
        config.Postgres.User = val_Postgres_User
    }
    val_Postgres_Password, ok := os.LookupEnv(OLXTRACKER_POSTGRES_PASSWORD_ENV)
    if !ok {
        missingVars = append(missingVars, ErrOlxtrackerPostgresPasswordEnvMissing)
    } else {
        config.Postgres.Password = val_Postgres_Password
    }
    val_Postgres_Host, ok := os.LookupEnv(OLXTRACKER_POSTGRES_HOST_ENV)
    if !ok {
        missingVars = append(missingVars, ErrOlxtrackerPostgresHostEnvMissing)
    } else {
        config.Postgres.Host = val_Postgres_Host
    }
    val_Postgres_Port, ok := os.LookupEnv(OLXTRACKER_POSTGRES_PORT_ENV)
    if !ok {
        missingVars = append(missingVars, ErrOlxtrackerPostgresPortEnvMissing)
    } else {
        parsed, err := strconv.Atoi(val_Postgres_Port)
        if err != nil {
            formatVars = append(formatVars, ErrOlxtrackerPostgresPortEnvInvalid)
        } else {
            config.Postgres.Port = parsed
        }
    }
    val_Postgres_Database, ok := os.LookupEnv(OLXTRACKER_POSTGRES_DATABASE_ENV)
    if !ok {
        missingVars = append(missingVars, ErrOlxtrackerPostgresDatabaseEnvMissing)
    } else {
        config.Postgres.Database = val_Postgres_Database
    }
    val_Postgres_Schema, ok := os.LookupEnv(OLXTRACKER_POSTGRES_SCHEMA_ENV)
    if !ok {
        missingVars = append(missingVars, ErrOlxtrackerPostgresSchemaEnvMissing)
    } else {
        config.Postgres.Schema = val_Postgres_Schema
    }

    if len(missingVars) > 0 || len(formatVars) > 0 {
        var verr error
        if len(missingVars) > 0 {
            verr = errors.Join(verr, MissingEnvVarsError{vars: missingVars})
        }
        if len(formatVars) > 0 {
            verr = errors.Join(verr, InvalidEnvVarsError{vars: missingVars})
        }
        return Config{}, verr
    }

    return config, nil
}

type MissingEnvVarsError struct {
	vars []error
}

func (m MissingEnvVarsError) Unwrap() []error {
	return m.vars
}

func (m MissingEnvVarsError) Error() string {
	if len(m.vars) == 0 {
		return ""
	}
	varsstr := make([]string, 0, len(m.vars))
	for _, v := range m.vars {
		varsstr = append(varsstr, v.Error())
	}
	return "envs " + strings.Join(varsstr, ",") + " are not set"
}

type InvalidEnvVarsError struct {
	vars []error
}

func (m InvalidEnvVarsError) Unwrap() []error {
	return m.vars
}

func (m InvalidEnvVarsError) Error() string {
	if len(m.vars) == 0 {
		return ""
	}
	varsstr := make([]string, 0, len(m.vars))
	for _, v := range m.vars {
		varsstr = append(varsstr, v.Error())
	}
	return "envs " + strings.Join(varsstr, ",") + " have an invalid value"
}
